### PR TITLE
*ADD* Fallback: Added .jsx suffix support for new components (Resolve…

### PR DESCRIPTION
**Pull request by weblogixx**
As promised :). This is a possible solution for the js/jsx "problem".
It adds the option to use .jsx as component filename on setup.

It is not throughoutly tested, but should work fine (unit tests are all passing, files and specs are generated correctly).

Please tell me what you think of it.

### CODE REVIEW

**Comment by newtriks** [comment]
@weblogixx awesome sauce mate thanks for doing this. Could you please add a little something to the README? https://github.com/newtriks/generator-react-webpack#options

**Comment by weblogixx** [comment]
Done :)

**Comment by newtriks** [comment]
@weblogixx just went to merge but there are some conflicts related to previous commits. Could you take a peek mate?

**Comment by weblogixx** [comment]
@newtricks: Fine, will merge it tomorrow :-)

**Comment by weblogixx** [comment]
@newtriks: Done.

**Comment by newtriks** [comment]
@weblogixx nice one mate

**Pull request merged**
