### PR TITLE
Add support for Flux

### PR DESCRIPTION
**Pull request by CrshOverride**
The generator is great for React applications. I'm slowly falling for webpack...but that's another story...

Unfortunately, adding Flux on top of the generated application is a bit of a chore as you have to revert to creating files by hand in the directory structure. I'm not sure if there's any interest in adding generator support, but I took a stab at it and wanted to give back if it's desired.

If you chose Flux support during app initialization, the generator will:

1. Install the `flux`, `events`, and `object-assign` npm packages.
2. Create your App Dispatcher

And you also gain two new generators:

1. Action
2. Store

### CODE REVIEW

**Comment by newtriks** [comment]
@CrshOverride thanks for this, I will take a look mate.

**Comment by newtriks** [comment]
@CrshOverride this looks great, there is a merge conflict however since the last merge...

**Comment by CrshOverride** [comment]
@newtriks I'll merge in and take care of any conflicts as soon as I can. Thanks for taking a look!

**Comment by CrshOverride** [comment]
@newtriks - Merge conflicts have been resolved and pushed.

**Comment by newtriks** [comment]
@CrshOverride nice one man thanks!

**Pull request merged**
