### PR TITLE
Update to React 0.12.2

### PR DESCRIPTION
**Pull request by andrewliebchen**
As requested in https://github.com/newtriks/generator-react-webpack/issues/36. I'm a designer/developer, so please double-check my work! :smile: 

Thanks for the great generator...I use it all the time!

### CODE REVIEW

**Comment by newtriks** [comment]
Hi @andrewliebchen thank you for the pull request, I will review and merge asap :+1:

**Comment by victor-homyakov** [comment]
Reach Router's API changed substantially, so app generated with routing does not work entirely
https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md#010x---011x

**Comment by andrewliebchen** [comment]
Hmm, wonder if 0.10.x works with React 0.12.x.

**Comment by ColCh** [comment]
6to5 supports jsx, so no jsx loader needed for es6 mode

**Comment by AlanVerbner** [comment]
As @victor-homyakov , routes didn't work for me. I was getting *Uncaught TypeError: Cannot read property '_mockedReactClassConstructor' of undefined*. Once I changed this i got it working:

```javascript
var Router = require('react-router');
var Route = Router.Route;

var routes = (
    <Route handler={FluxTestApp}>
        <Route name="/" handler={FluxTestApp}/>
    </Route>
);

var content = document.getElementById('content');

Router.run(routes, Router.HistoryLocation, function (Handler) {
    React.render(<Handler/>, content);
});

// or default to hash location
Router.run(routes, function (Handler) {
    React.render(<Handler/>, content);
});
```
This is the first time I play around with React so I'm not sure if this is the correct solution.

**Pull request merged**
